### ISSUE TITLE
More user friendly README.md

### ISSUE THREAD

**Issue by shapkarin** [shapkarin/extend-saga-routines#31]
Make the introduction with basic explanation as much simple and understandable as it can be.
Leave all the rest as docs section.

**Comment by Styrle** [comment]
Hi there, I would love to be assigned to this. I have previously created readme's similar to this and would love to take it on.

**Comment by shapkarin** [comment]
@Styrle hello. That’s would be great. PRs are welcome. I will assign this
issue to you when I will back to home.

**Comment by shapkarin** [comment]
@Styrle also related issue #29

**Comment by shapkarin** [comment]
@Styrle how it's going? maybe you can upload some version and we can make it together?

**Comment by Styrle** [comment]
Ok I can do that

**Comment by Styrle** [comment]
You should be able to pull it now

**Comment by shapkarin** [comment]
Closed with #36 #37 #38

**Comment by shapkarin** [comment]
@Styrle thanks for your help. Readme got much better typographyc.
